Remove some stage

diff --git a/.github/workflows/terraform-dev.yml b/.github/workflows/terraform-dev.yml
--- a/.github/workflows/terraform-dev.yml
+++ b/.github/workflows/terraform-dev.yml
@@ -50,26 +50,26 @@ jobs:
         run: terraform fmt -check
         continue-on-error: false
 
-      - name: Validate Terraform
-        id: validate
-        if: (success() || failure())
-        run: terraform validate
-        continue-on-error: false
+      # - name: Validate Terraform
+      #   id: validate
+      #   if: (success() || failure())
+      #   run: terraform validate
+      #   continue-on-error: false
 
-      - name: Plan Terraform
-        id: plan
-        if: (success() || failure())
-        env:
-          TF_IN_AUTOMATION: true
-          TF_WORKSPACE: default
-        run: terraform plan
+      # - name: Plan Terraform
+      #   id: plan
+      #   if: (success() || failure())
+      #   env:
+      #     TF_IN_AUTOMATION: true
+      #     TF_WORKSPACE: default
+      #   run: terraform plan
       
-      - name: Apply Terraform
-        id: apply
-        if: (success() || failure())
-        env:
-          TF_IN_AUTOMATION: true
-          TF_WORKSPACE: default
-        run: terraform apply -auto-approve
+      # - name: Apply Terraform
+      #   id: apply
+      #   if: (success() || failure())
+      #   env:
+      #     TF_IN_AUTOMATION: true
+      #     TF_WORKSPACE: default
+      #   run: terraform apply -auto-approve
 
 
